//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab2CLient.OrderServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrderServiceReference.IOrderService")]
    public interface IOrderService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlOf_OrderDTO/read", ReplyAction="http://tempuri.org/IControlOf_OrderDTO/readResponse")]
        Contract.DTO.OrderDTO[] read();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlOf_OrderDTO/read", ReplyAction="http://tempuri.org/IControlOf_OrderDTO/readResponse")]
        System.Threading.Tasks.Task<Contract.DTO.OrderDTO[]> readAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlOf_OrderDTO/readById", ReplyAction="http://tempuri.org/IControlOf_OrderDTO/readByIdResponse")]
        Contract.DTO.OrderDTO readById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlOf_OrderDTO/readById", ReplyAction="http://tempuri.org/IControlOf_OrderDTO/readByIdResponse")]
        System.Threading.Tasks.Task<Contract.DTO.OrderDTO> readByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlOf_OrderDTO/create", ReplyAction="http://tempuri.org/IControlOf_OrderDTO/createResponse")]
        void create(Contract.DTO.OrderDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlOf_OrderDTO/create", ReplyAction="http://tempuri.org/IControlOf_OrderDTO/createResponse")]
        System.Threading.Tasks.Task createAsync(Contract.DTO.OrderDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlOf_OrderDTO/update", ReplyAction="http://tempuri.org/IControlOf_OrderDTO/updateResponse")]
        void update(Contract.DTO.OrderDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlOf_OrderDTO/update", ReplyAction="http://tempuri.org/IControlOf_OrderDTO/updateResponse")]
        System.Threading.Tasks.Task updateAsync(Contract.DTO.OrderDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlOf_OrderDTO/deleteById", ReplyAction="http://tempuri.org/IControlOf_OrderDTO/deleteByIdResponse")]
        void deleteById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlOf_OrderDTO/deleteById", ReplyAction="http://tempuri.org/IControlOf_OrderDTO/deleteByIdResponse")]
        System.Threading.Tasks.Task deleteByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrderServiceChannel : Lab2CLient.OrderServiceReference.IOrderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderServiceClient : System.ServiceModel.ClientBase<Lab2CLient.OrderServiceReference.IOrderService>, Lab2CLient.OrderServiceReference.IOrderService {
        
        public OrderServiceClient() {
        }
        
        public OrderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Contract.DTO.OrderDTO[] read() {
            return base.Channel.read();
        }
        
        public System.Threading.Tasks.Task<Contract.DTO.OrderDTO[]> readAsync() {
            return base.Channel.readAsync();
        }
        
        public Contract.DTO.OrderDTO readById(int id) {
            return base.Channel.readById(id);
        }
        
        public System.Threading.Tasks.Task<Contract.DTO.OrderDTO> readByIdAsync(int id) {
            return base.Channel.readByIdAsync(id);
        }
        
        public void create(Contract.DTO.OrderDTO entity) {
            base.Channel.create(entity);
        }
        
        public System.Threading.Tasks.Task createAsync(Contract.DTO.OrderDTO entity) {
            return base.Channel.createAsync(entity);
        }
        
        public void update(Contract.DTO.OrderDTO entity) {
            base.Channel.update(entity);
        }
        
        public System.Threading.Tasks.Task updateAsync(Contract.DTO.OrderDTO entity) {
            return base.Channel.updateAsync(entity);
        }
        
        public void deleteById(int id) {
            base.Channel.deleteById(id);
        }
        
        public System.Threading.Tasks.Task deleteByIdAsync(int id) {
            return base.Channel.deleteByIdAsync(id);
        }
    }
}
