//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab2CLient.PartsServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PartsServiceReference1.IPartsService")]
    public interface IPartsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlOf_PartDTO/read", ReplyAction="http://tempuri.org/IControlOf_PartDTO/readResponse")]
        Contract.DTO.PartDTO[] read();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlOf_PartDTO/read", ReplyAction="http://tempuri.org/IControlOf_PartDTO/readResponse")]
        System.Threading.Tasks.Task<Contract.DTO.PartDTO[]> readAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlOf_PartDTO/readById", ReplyAction="http://tempuri.org/IControlOf_PartDTO/readByIdResponse")]
        Contract.DTO.PartDTO readById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlOf_PartDTO/readById", ReplyAction="http://tempuri.org/IControlOf_PartDTO/readByIdResponse")]
        System.Threading.Tasks.Task<Contract.DTO.PartDTO> readByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlOf_PartDTO/create", ReplyAction="http://tempuri.org/IControlOf_PartDTO/createResponse")]
        void create(Contract.DTO.PartDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlOf_PartDTO/create", ReplyAction="http://tempuri.org/IControlOf_PartDTO/createResponse")]
        System.Threading.Tasks.Task createAsync(Contract.DTO.PartDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlOf_PartDTO/update", ReplyAction="http://tempuri.org/IControlOf_PartDTO/updateResponse")]
        void update(Contract.DTO.PartDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlOf_PartDTO/update", ReplyAction="http://tempuri.org/IControlOf_PartDTO/updateResponse")]
        System.Threading.Tasks.Task updateAsync(Contract.DTO.PartDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlOf_PartDTO/deleteById", ReplyAction="http://tempuri.org/IControlOf_PartDTO/deleteByIdResponse")]
        void deleteById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlOf_PartDTO/deleteById", ReplyAction="http://tempuri.org/IControlOf_PartDTO/deleteByIdResponse")]
        System.Threading.Tasks.Task deleteByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPartsServiceChannel : Lab2CLient.PartsServiceReference1.IPartsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PartsServiceClient : System.ServiceModel.ClientBase<Lab2CLient.PartsServiceReference1.IPartsService>, Lab2CLient.PartsServiceReference1.IPartsService {
        
        public PartsServiceClient() {
        }
        
        public PartsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PartsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PartsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PartsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Contract.DTO.PartDTO[] read() {
            return base.Channel.read();
        }
        
        public System.Threading.Tasks.Task<Contract.DTO.PartDTO[]> readAsync() {
            return base.Channel.readAsync();
        }
        
        public Contract.DTO.PartDTO readById(int id) {
            return base.Channel.readById(id);
        }
        
        public System.Threading.Tasks.Task<Contract.DTO.PartDTO> readByIdAsync(int id) {
            return base.Channel.readByIdAsync(id);
        }
        
        public void create(Contract.DTO.PartDTO entity) {
            base.Channel.create(entity);
        }
        
        public System.Threading.Tasks.Task createAsync(Contract.DTO.PartDTO entity) {
            return base.Channel.createAsync(entity);
        }
        
        public void update(Contract.DTO.PartDTO entity) {
            base.Channel.update(entity);
        }
        
        public System.Threading.Tasks.Task updateAsync(Contract.DTO.PartDTO entity) {
            return base.Channel.updateAsync(entity);
        }
        
        public void deleteById(int id) {
            base.Channel.deleteById(id);
        }
        
        public System.Threading.Tasks.Task deleteByIdAsync(int id) {
            return base.Channel.deleteByIdAsync(id);
        }
    }
}
