//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        public int ItemNo { get; set; }
        public int OrderNo { get; set; }
        public int PartNo { get; set; }
        public int Count { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Parts Parts { get; set; }
    }
}
